---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:
  - name: lint
    image: golangci/golangci-lint:v1.57.2
    commands:
     - golangci-lint run -v --timeout 10m ./...

  - name: test
    image: golang:1.22
    commands:
      - go test -coverprofile cover.out -v ./...
      - go tool cover -func cover.out
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: build
    image: ghcr.io/codestation/drone-kaniko
    settings:
      repo: registry.megpoid.dev/codestation/drone-kube-proxy
      tags:
        - latest
        - ${DRONE_TAG}
      registry: registry.megpoid.dev
      config:
        from_secret: registry_credentials
      build_args:
        - CI_COMMIT_TAG=${DRONE_TAG}
      build_args_from_env:
        - goproxy
    environment:
      goproxy:
        from_secret: goproxy_url
    when:
      event:
        - tag

trigger:
  event:
    - push
    - tag
