global:
  provider: linode
  interval: 5m
dns:
  - hostname: vpn
    zone: assetec.org
    labels:
      assetec.org/role: infrastructure
  - hostname: vm-swarm
    zone: assetec.org
    labels:
      assetec.org/role: infrastructure
